# Generated by Django 5.2.7 on 2026-01-04 06:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0002_alter_review_options_alter_review_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
