# Generated by Django 6.0 on 2026-01-05 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours', '0003_booking_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('PAYPAL', 'PayPal'), ('STRIPE', 'Stripe'), ('MOMO', 'MoMo'), ('ZALOPAY', 'ZaloPay')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('is_paid', models.BooleanField(default=False)),
                ('transaction_id', models.CharField(blank=True, max_length=255, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='tours.booking')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
