# Generated by Django 4.2.25 on 2025-12-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour_tech', '0002_booking_role_service_user_avatar_bookinghotel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
